"""Python codegen against a live Keystone node — the Python sibling of
``tpt-sdk/src/bin/typegen.rs`` and ``@tpt/sdk-web``'s ``bin/typegen.ts``
(same source data, ``information_schema.columns``, different transport:
this one talks the Postgres wire protocol via ``KeystoneClient`` directly).
Emits one dataclass + ``TableDef`` per table to stdout.

Usage::

    python -m tpt_sdk.typegen 127.0.0.1:5432 > generated_schema.py
"""

from __future__ import annotations

import asyncio
import sys
from typing import Dict, List, Tuple

from .client import KeystoneClient

_TYPE_MAP = {
    "int2": "int",
    "int4": "int",
    "int8": "int",
    "float4": "float",
    "float8": "float",
    "bool": "bool",
}


def _pascal_case(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.replace("-", "_").split("_") if part)


def _python_type_for(keystone_type: str) -> str:
    return _TYPE_MAP.get(keystone_type, "str")


async def _fetch_columns(addr: str) -> List[Tuple[str, str, str]]:
    host, _, port = addr.partition(":")
    client = KeystoneClient(host=host or "127.0.0.1", port=int(port) if port else 5432)
    await client.connect()
    try:
        result = await client.query(
            "SELECT table_name, column_name, data_type FROM information_schema.columns "
            "WHERE table_schema = 'public' ORDER BY table_name, ordinal_position"
        )
        return [(row.table_name, row.column_name, row.data_type) for row in result.rows]
    finally:
        await client.close()


def _render(columns: List[Tuple[str, str, str]]) -> str:
    tables: Dict[str, List[Tuple[str, str]]] = {}
    for table_name, column_name, data_type in columns:
        tables.setdefault(table_name, []).append((column_name, data_type))

    out = [
        "# Generated by `python -m tpt_sdk.typegen` — do not hand-edit.",
        "from dataclasses import dataclass",
        "from typing import Optional",
        "",
        "from tpt_sdk.query_builder import TableDef",
        "",
    ]
    for table_name, cols in tables.items():
        class_name = _pascal_case(table_name)
        out.append("@dataclass")
        out.append(f"class {class_name}:")
        for column_name, data_type in cols:
            out.append(f"    {column_name}: Optional[{_python_type_for(data_type)}] = None")
        out.append("")
        cols_list = ", ".join(f'"{c}"' for c, _ in cols)
        out.append(f'{class_name}Table: TableDef["{class_name}"] = TableDef(name="{table_name}", columns=[{cols_list}])')
        out.append("")
    return "\n".join(out)


def main() -> None:
    addr = sys.argv[1] if len(sys.argv) > 1 else "127.0.0.1:5432"
    columns = asyncio.run(_fetch_columns(addr))
    sys.stdout.write(_render(columns))


if __name__ == "__main__":
    main()
