// Typed query builder — Phase 5's "AI-optimised SDK" checklist item.
// Different from `models.ts`'s existing per-engine builders (those take a
// bare `table: string` and hand back untyped rows): this one is
// schema-driven — a `TableDef<Row>` (hand-written, or generated by
// `bin/typegen.ts` from a live `GET /schema`) carries the row's TypeScript
// shape *and* its column list, so `.select()`/`.whereEq()` are
// autocompleted against real columns and `.fetch()` returns `Row[]`, not
// `Record<string, string | null>[]`.
//
// Still just a `{ sql, params }` string builder underneath — same
// philosophy as `models.ts`: give real typing and typo-safety, don't hide
// SQL behind an ORM abstraction that can't express an arbitrary query.
// `.build()` is always available as the escape hatch into
// `KeystoneClient.query`/`queryTyped` directly.

export interface BuiltQuery {
  sql: string;
  params: unknown[];
}

/** Metadata a generated (or hand-written) per-table definition provides. */
export interface TableDef<Row> {
  name: string;
  columns: (keyof Row & string)[];
}

export function table<Row>(name: string, columns: (keyof Row & string)[]): TableDef<Row> {
  return { name, columns };
}

function quoteIdent(ident: string): string {
  return `"${ident.replace(/"/g, '""')}"`;
}

type Order = "ASC" | "DESC";

/** Minimal shape `fetch()` needs from a client — satisfied by both
 * `KeystoneClient.query` (sdk-web/sdk-edge, HTTP bridge) and
 * `Conn.query`-style wire clients (sdk-server), so this builder isn't tied
 * to one transport. */
export interface Queryable {
  query(sql: string, params?: unknown[]): Promise<{ rows: unknown[] }>;
}

export class TypedQueryBuilder<Row> {
  private cols: (keyof Row & string)[];
  private filters: Array<[keyof Row & string, unknown]> = [];
  private orderCol?: keyof Row & string;
  private orderDir: Order = "ASC";
  private limitN?: number;
  private offsetN?: number;

  constructor(private readonly def: TableDef<Row>) {
    this.cols = def.columns;
  }

  /** Restricts selected columns (default: every column in the table def). */
  select(cols: (keyof Row & string)[]): this {
    this.cols = cols;
    return this;
  }

  /** Adds a `column = value` filter, AND-ed with any others already added.
   * Always a bind parameter, never inlined into the SQL text. */
  whereEq<K extends keyof Row & string>(col: K, value: Row[K]): this {
    this.filters.push([col, value]);
    return this;
  }

  orderBy(col: keyof Row & string, dir: Order = "ASC"): this {
    this.orderCol = col;
    this.orderDir = dir;
    return this;
  }

  limit(n: number): this {
    this.limitN = n;
    return this;
  }

  offset(n: number): this {
    this.offsetN = n;
    return this;
  }

  /** Renders `(sql, params)` — `params[i]` binds to `$${i + 1}` in `sql`. */
  build(): BuiltQuery {
    const cols = this.cols.map(quoteIdent).join(", ");
    let sql = `SELECT ${cols} FROM ${quoteIdent(this.def.name)}`;
    const params: unknown[] = [];

    if (this.filters.length) {
      const clauses = this.filters.map(([col], i) => `${quoteIdent(col)} = $${i + 1}`);
      sql += ` WHERE ${clauses.join(" AND ")}`;
      params.push(...this.filters.map(([, v]) => v));
    }
    if (this.orderCol) {
      sql += ` ORDER BY ${quoteIdent(this.orderCol)} ${this.orderDir}`;
    }
    if (this.limitN !== undefined) {
      sql += ` LIMIT ${this.limitN}`;
    }
    if (this.offsetN !== undefined) {
      sql += ` OFFSET ${this.offsetN}`;
    }
    return { sql, params };
  }

  /** Builds and executes against `client` in one step. */
  async fetch(client: Queryable): Promise<Row[]> {
    const { sql, params } = this.build();
    const result = await client.query(sql, params);
    return result.rows as Row[];
  }
}

export function from<Row>(def: TableDef<Row>): TypedQueryBuilder<Row> {
  return new TypedQueryBuilder(def);
}
