"""Typed query builder — Phase 5's "AI-optimised SDK" checklist item, the
Python sibling of the Rust SDK's ``query_builder.rs`` and
``@tpt/sdk-web``/``@tpt/sdk-server``'s ``query-builder.ts``. Same design:
a schema-driven ``TableDef`` (hand-written, or generated by ``typegen.py``
from a live server's ``information_schema``) plus a chainable
``QueryBuilder`` that renders a parameterized ``(sql, params)`` pair instead
of the caller hand-formatting SQL text.

Pure sugar over ``KeystoneClient.query_params`` — ``.build()`` is always
available so callers aren't locked out of anything the builder doesn't
expose, the same escape-hatch philosophy every other SDK in this repo
follows.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Generic, List, Optional, Sequence, Tuple, TypeVar

from .client import KeystoneClient, QueryResult

T = TypeVar("T")


@dataclass(frozen=True)
class TableDef(Generic[T]):
    """Minimal per-table metadata the builder needs: table name and column
    list, in ``SELECT *``-equivalent order. ``typegen.py`` generates one of
    these per table; nothing stops a caller writing one by hand for a table
    typegen was never pointed at.
    """

    name: str
    columns: Sequence[str]


class QueryBuilder(Generic[T]):
    def __init__(self, table: TableDef[T]) -> None:
        self._table = table
        self._columns: List[str] = list(table.columns)
        self._filters: List[Tuple[str, Any]] = []
        self._order: Optional[Tuple[str, str]] = None
        self._limit: Optional[int] = None
        self._offset: Optional[int] = None

    def select(self, columns: Sequence[str]) -> "QueryBuilder[T]":
        self._columns = list(columns)
        return self

    def filter_eq(self, column: str, value: Any) -> "QueryBuilder[T]":
        """Adds a ``column = value`` filter, AND-ed with any others already
        added. Always sent as a bind parameter, never inlined into the SQL
        text."""
        self._filters.append((column, value))
        return self

    def order_by(self, column: str, desc: bool = False) -> "QueryBuilder[T]":
        self._order = (column, "DESC" if desc else "ASC")
        return self

    def limit(self, n: int) -> "QueryBuilder[T]":
        self._limit = n
        return self

    def offset(self, n: int) -> "QueryBuilder[T]":
        self._offset = n
        return self

    def build(self) -> Tuple[str, List[Any]]:
        """Renders ``(sql, params)`` — ``params[i]`` binds to ``${i+1}`` in
        ``sql``, matching ``KeystoneClient.query_params``'s convention."""
        sql = f"SELECT {', '.join(self._columns)} FROM {self._table.name}"
        params: List[Any] = []

        if self._filters:
            clauses = [f"{col} = ${i + 1}" for i, (col, _) in enumerate(self._filters)]
            sql += " WHERE " + " AND ".join(clauses)
            params.extend(value for _, value in self._filters)
        if self._order is not None:
            column, direction = self._order
            sql += f" ORDER BY {column} {direction}"
        if self._limit is not None:
            sql += f" LIMIT {self._limit}"
        if self._offset is not None:
            sql += f" OFFSET {self._offset}"
        return sql, params

    async def fetch(self, client: KeystoneClient) -> QueryResult:
        """Builds and executes against ``client`` in one step."""
        sql, params = self.build()
        return await client.query_params(sql, params)
