# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flux_grpc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66lux_grpc.proto\"\"\n\x12\x43reateTopicRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x15\n\x13\x43reateTopicResponse\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"Y\n\x06Record\x12\x0e\n\x06offset\x18\x01 \x01(\x04\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\x12\r\n\x05topic\x18\x05 \x01(\t\"e\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\x12\x15\n\rhas_partition\x18\x04 \x01(\x08\x12\x11\n\tpartition\x18\x05 \x01(\r\"4\n\x0fPublishResponse\x12\x11\n\tpartition\x18\x01 \x01(\r\x12\x0e\n\x06offset\x18\x02 \x01(\x04\"K\n\x0bPollRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x11\n\tpartition\x18\x02 \x01(\r\x12\r\n\x05group\x18\x03 \x01(\t\x12\x0b\n\x03max\x18\x04 \x01(\r\"(\n\x0cPollResponse\x12\x18\n\x07records\x18\x01 \x03(\x0b\x32\x07.Record2\xbe\x01\n\x04\x46lux\x12)\n\tSubscribe\x12\x11.SubscribeRequest\x1a\x07.Record0\x01\x12,\n\x07Publish\x12\x0f.PublishRequest\x1a\x10.PublishResponse\x12#\n\x04Poll\x12\x0c.PollRequest\x1a\r.PollResponse\x12\x38\n\x0b\x43reateTopic\x12\x13.CreateTopicRequest\x1a\x14.CreateTopicResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flux_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETOPICREQUEST']._serialized_start=19
  _globals['_CREATETOPICREQUEST']._serialized_end=53
  _globals['_CREATETOPICRESPONSE']._serialized_start=55
  _globals['_CREATETOPICRESPONSE']._serialized_end=76
  _globals['_SUBSCRIBEREQUEST']._serialized_start=78
  _globals['_SUBSCRIBEREQUEST']._serialized_end=111
  _globals['_RECORD']._serialized_start=113
  _globals['_RECORD']._serialized_end=202
  _globals['_PUBLISHREQUEST']._serialized_start=204
  _globals['_PUBLISHREQUEST']._serialized_end=305
  _globals['_PUBLISHRESPONSE']._serialized_start=307
  _globals['_PUBLISHRESPONSE']._serialized_end=359
  _globals['_POLLREQUEST']._serialized_start=361
  _globals['_POLLREQUEST']._serialized_end=436
  _globals['_POLLRESPONSE']._serialized_start=438
  _globals['_POLLRESPONSE']._serialized_end=478
  _globals['_FLUX']._serialized_start=481
  _globals['_FLUX']._serialized_end=671
# @@protoc_insertion_point(module_scope)
